name: packaging-Pipeline

run-name: packaging triggered by ${{ github.actor }}

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend # deo-webapp-ws25-backend

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    permission:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: checkout repository code
        uses: actions/checkout@v4
      - name: log in to container REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }
      - name: extract metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
      - name: build an push images
        uses: docker/build-push-action@v6
        with:
          context: ./Deo.Backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: generate artifact attestations
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
